/**
 *  StatusCode 400
 */

export const ERROR_WITH_STATUS_CODE_400_IDENTIFY = {
  USER_WAS_SIGNED_UP_WITH_DEVICE: 1,
  WRONG_PASS: 2,
  NO_CLIENT_INFOR: 3,
  DEVICE_WAS_SIGNED_UP: 4,
};

export const ERROR_WITH_STATUS_CODE_400_ATTENDANCE = {
  OUT_OF_TIME: 2,
  INVALID_QR_CODE: 3,
};

/**
 *  StatusCode 401
 */

export const ERROR_WITH_STATUS_CODE_401_ATTENDANCE = {
  WRONG_WIFI: 4,
};

export const ERROR_WITH_STATUS_CODE_401_LOGIN = {
  WRONG_USERNAME: 1,
  WRONG_PASS: 2,
};

/**
 *  StatusCode 404
 */

export const ERROR_WITH_STATUS_CODE_404_ATTENDANCE = {
  WRONG_ATTENDANCE_INFO: 1,
};

export const ERROR_WITH_STATUS_CODE_404_ABSENT_EARLY_LATE = {
  NO_INFOR_CALENDAR: 1,
};

export const ERROR_WITH_STATUS_CODE_404_ADMIN_ACCEPT = {
  NO_LETTER: 1,
  NO_INFOR_CALENDAR: 2,
};
